# Site settings
title:            tollmanz.com
baseurl:          ''
url:              'http://tollmanz.com'
twitter_username: tollmanz
github_username:  tollmanz
local:            true
permalink:        /:title/
exclude:          [
  'Gruntfile.js',
  'package.json'
]
sass:
  style: compressed