# Site settings
title:            tollmanz.com
baseurl:          ''
url:              'https://www.tollmanz.com'
twitter_username: tollmanz
github_username:  tollmanz
local:            true
permalink:        /:title/
exclude:          [
  'Gruntfile.js',
  'package.json'
]
sass:
  style: compressed
kramdown:
  smart_quotes: ["apos", "apos", "quot", "quot"]
gems:
  - jekyll-sitemap
